# Generated by Django 5.0 on 2023-12-09 14:20

import MusicApp.music_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_name",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            MusicApp.music_app.validators.username_validator,
                        ],
                        verbose_name="Album name",
                    ),
                ),
                ("artist", models.CharField(max_length=30)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop Music", "Pop Music"),
                            ("Jazz Music", "Jazz Music"),
                            ("R&B Music", "R N B Music"),
                            ("Rock Music", "Rock Music"),
                            ("Country Music", "Country Music"),
                            ("Dance Music", "Dance Music"),
                            ("Hip Hop Music", "Hip Hop Music"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(verbose_name="Image URL")),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            MusicApp.music_app.validators.username_validator,
                        ],
                        verbose_name="Username",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="Image URL"),
                ),
            ],
        ),
    ]
